CREATE DATABASE CozyHavenStay;
USE CozyHavenStay;

-- User Table
CREATE TABLE [User] (
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    Password NVARCHAR(255) NOT NULL,
    Gender NVARCHAR(10) NOT NULL,
    ContactNumber NVARCHAR(20) NOT NULL,
    Address NVARCHAR(255) NOT NULL,
    AccountType NVARCHAR(50) DEFAULT('Guest'),
    ProfileImage NVARCHAR(255)
);

-- Admin Table
CREATE TABLE Admin (
    AdminID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    Password NVARCHAR(255) NOT NULL,
    AccountType NVARCHAR(50) DEFAULT('Admin')
);

-- HotelOwner Table
CREATE TABLE HotelOwner (
    OwnerID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    Password NVARCHAR(255) NOT NULL,
    AccountType NVARCHAR(50) DEFAULT('Owner')
);

-- Hotel Table
CREATE TABLE Hotel (
    HotelID INT IDENTITY(1,1) PRIMARY KEY,
    OwnerID INT FOREIGN KEY REFERENCES HotelOwner(OwnerID) ON DELETE CASCADE,
    Name NVARCHAR(100) NOT NULL,
    Location NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX) NOT NULL,
    Amenities NVARCHAR(MAX) NOT NULL
);

-- HotelImage Table
CREATE TABLE HotelImage (
    ImageID INT IDENTITY(1,1) PRIMARY KEY,
    HotelID INT FOREIGN KEY REFERENCES Hotel(HotelID) ON DELETE CASCADE,
    ImageURL NVARCHAR(255)
);

-- Room Table
CREATE TABLE Room (
    RoomID INT IDENTITY(1,1) PRIMARY KEY,
    HotelID INT FOREIGN KEY REFERENCES Hotel(HotelID) ON DELETE CASCADE,
    RoomType NVARCHAR(50) NOT NULL,
    MaxOccupancy INT NOT NULL,
    BedType NVARCHAR(50) NOT NULL,
    BaseFare DECIMAL(10, 2) NOT NULL,
    RoomSize NVARCHAR(50) NOT NULL,
    ACStatus NVARCHAR(3) NOT NULL,
    CONSTRAINT CHK_AC_Status CHECK (ACStatus IN ('AC', 'Non-AC')),
);

-- RoomImage Table
CREATE TABLE RoomImage (
    ImageID INT IDENTITY(1,1) PRIMARY KEY,
    RoomID INT FOREIGN KEY REFERENCES Room(RoomID) ON DELETE CASCADE,
    ImageURL NVARCHAR(255)
);

-- Booking Table
CREATE TABLE Booking (
    BookingID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT FOREIGN KEY REFERENCES [User](UserID) ON DELETE CASCADE,
    RoomID INT FOREIGN KEY REFERENCES Room(RoomID) ON DELETE CASCADE,
    NumberOfGuests INT NOT NULL,
    CheckInDate DATETIME NOT NULL,
    CheckOutDate DATETIME NOT NULL,
    TotalFare DECIMAL(10, 2) NOT NULL,
    Status NVARCHAR(20) NOT NULL,
    RefundAmount DECIMAL(10, 2)
);

-- Review Table
CREATE TABLE Review (
    ReviewID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT FOREIGN KEY REFERENCES [User](UserID),
    HotelID INT FOREIGN KEY REFERENCES Hotel(HotelID) ON DELETE CASCADE,
    Rating INT NOT NULL,
    Comments NVARCHAR(MAX) NOT NULL
);

-- Refund Table
CREATE TABLE Refund (
    RefundID INT IDENTITY(1,1) PRIMARY KEY,
    BookingID INT FOREIGN KEY REFERENCES Booking(BookingID) ON DELETE CASCADE,
    RefundAmount DECIMAL(10, 2) NOT NULL,
    Reason NVARCHAR(MAX),
    RefundDate DATETIME DEFAULT GETDATE(),
	RefundStatus NVARCHAR(100) DEFAULT ('In Progress')
);

-- Log Table
CREATE TABLE Log (
    LogID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT FOREIGN KEY REFERENCES [User](UserID),
    Action NVARCHAR(100),
    Timestamp DATETIME DEFAULT GETDATE()
);